services:
  db:
    image: postgres:15
    container_name: secure-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: secure-app
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: secure_db
      DB_USER: user
      DB_PASS: password
    ports:
      - "8000:8000"
